(function(){
  'use strict';
  const id=document.getElementById('intakeId'),message=document.getElementById('editorMessage'),workspace=document.getElementById('editorWorkspace'),source=document.getElementById('sourcePreview'),result=document.getElementById('resultCanvas'),processButton=document.getElementById('removeBackground'),confirm=document.getElementById('confirmResult'),save=document.getElementById('saveResult'),download=document.getElementById('downloadResult');
  let mediaRef=null,outputBlob=null;
  function notice(text,error){message.hidden=false;message.className=error?'admin-error':'admin-message';message.textContent=text}
  function base64(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(new Error('Hasil foto tidak dapat dibaca.'));reader.readAsDataURL(blob)})}
  function imageReady(image){if(image.complete&&image.naturalWidth)return Promise.resolve();return new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(new Error('Foto profil tidak dapat dibuka.'))})}
  async function load(){
    const intakeId=id.value.trim();if(!intakeId){notice('Masukkan ID intake terlebih dahulu.',true);return}
    notice('Memuat foto profil privat…');mediaRef=null;outputBlob=null;confirm.checked=false;confirm.disabled=true;save.disabled=true;download.disabled=true;processButton.disabled=true;
    try{const snap=await db.collection('trader_media').where('ownerId','==',intakeId).where('mediaType','==','PROFILE').limit(5).get();let found=null;snap.forEach(doc=>{const data=doc.data();if(!found&&data.ownerType==='TRADER_INTAKE'&&data.dataBase64)found={ref:doc.ref,...data}});if(!found)throw new Error('Foto profil untuk pendaftaran ini belum ditemukan.');mediaRef=found.ref;source.src=`data:${found.mime};base64,${found.dataBase64}`;await imageReady(source);processButton.disabled=false;notice('Foto siap. Tekan “Hapus latar otomatis” lalu periksa seluruh tepinya.') }catch(error){notice(error.message||'Foto belum dapat dimuat.',true)}
  }
  async function process(){
    processButton.disabled=true;notice('Model sedang memisahkan pedagang dari latar. Proses pertama dapat memerlukan waktu untuk memuat model…');
    try{const canvas=await window.EPASAR_BACKGROUND.remove(source,{threshold:Number(document.getElementById('edgeThreshold').value)/100,maxSide:800});result.width=canvas.width;result.height=canvas.height;result.getContext('2d').clearRect(0,0,result.width,result.height);result.getContext('2d').drawImage(canvas,0,0);outputBlob=await window.EPASAR_BACKGROUND.webp(result,.82);if(outputBlob.size>55000)outputBlob=await window.EPASAR_BACKGROUND.webp(result,.68);if(outputBlob.size>55000)throw new Error('Hasil masih lebih besar dari 55 KB. Gunakan foto dengan komposisi lebih sederhana.');confirm.disabled=false;download.disabled=false;notice(`Pemrosesan selesai (${Math.round(outputBlob.size/1024)} KB). Periksa hasil sebelum menyimpan.`)}catch(error){console.error(error);notice('Latar belum dapat dihapus dengan baik. Periksa koneksi model atau gunakan foto asli.',true)}finally{processButton.disabled=false}
  }
  confirm.addEventListener('change',()=>{save.disabled=!(confirm.checked&&outputBlob&&mediaRef)});
  document.getElementById('loadPhoto').addEventListener('click',load);processButton.addEventListener('click',process);document.getElementById('edgeThreshold').addEventListener('change',()=>{if(source.src)process()});
  download.addEventListener('click',()=>{if(!outputBlob)return;const url=URL.createObjectURL(outputBlob),a=document.createElement('a');a.href=url;a.download='foto-pedagang-transparan.webp';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
  save.addEventListener('click',async()=>{if(!confirm.checked||!outputBlob||!mediaRef)return;save.disabled=true;notice('Menyimpan hasil terverifikasi…');try{const dataBase64=await base64(outputBlob);await mediaRef.update({mime:'image/webp',width:result.width,height:result.height,binaryBytes:outputBlob.size,base64Bytes:dataBase64.length,dataBase64,backgroundRemoval:{method:'MEDIAPIPE_SELFIE_SEGMENTER',reviewed:true,reviewedBy:firebase.auth().currentUser.uid,threshold:Number(document.getElementById('edgeThreshold').value)/100,modelVersion:'selfie_segmenter-float16-2023-05-07',modelSha256:'191ac9529ae506ee0beefa6b2c945a172dab9d07d1e802a290a4e4038226658b'},updatedAt:firebase.firestore.FieldValue.serverTimestamp()});notice('Foto transparan telah disimpan. Foto ini siap dipublikasikan saat berkas pedagang diproses.')}catch(error){notice('Hasil belum dapat disimpan. Periksa hak akses dan coba kembali.',true);save.disabled=false}});
  (async()=>{try{const profile=await window.EPASAR_AUTH.requireStaff(['SUPER_ADMIN','DISPERINDAG_ADMIN','TRADE_ADMIN','MARKET_ADMIN','TECH_ADMIN']);window.EPASAR_INTERNAL_UI?.setProfile(profile);workspace.hidden=false;message.hidden=true;id.value=new URLSearchParams(location.search).get('intake')||'';if(id.value)await load()}catch(error){notice('Halaman ini hanya tersedia untuk petugas administrasi yang berwenang.',true);setTimeout(()=>location.href='login.html',1200)}})();
}());
